libcamera2: Fix build error
BZ: 215530

Initialize newly introduced open_legacy member to avoid compilation
error: AtomHAL.cpp:86:1: sorry, unimplemented: non-trivial designated
initializers not supported

Change-Id: I28068a461396982a19a8104e71053a0ffde115f1
Signed-off-by: Laurent FERT <laurent.fert@intel.com>