libcamera2: fixes GCC 4.7 compilation
BZ: 104066

Due to C++11 changes, the compilation failed with GCC 4.7.
The failure was due to "narrowing conversions". Added
static_casts to fix the issue. Also fixes unsigned to signed
integer comparison.

Change-Id: Ib83c1dfc98f8e1be00cb5d87e85e3f91f1dfa6f3
Signed-off-by: Lassi Väätämöinen <lassix.vtminen@intel.com>
Reviewed-on: http://android.intel.com:8080/105529
Reviewed-by: Lampila, KalleX <kallex.lampila@intel.com>
Reviewed-by: Verdu, Miguel <miguel.verdu@intel.com>
Reviewed-by: Smith, Geoff <geoff.smith@intel.com>
Reviewed-by: Tuominen, TeemuX <teemux.tuominen@intel.com>
Reviewed-by: Chupin, Pavel V <pavel.v.chupin@intel.com>
Tested-by: Koski, Anttu <anttu.koski@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>